### ISSUE TITLE
Any plans for a gnuradio 3.10 version?

### ISSUE THREAD

**Issue by kgarrels** [daniestevez/gr-hermeslite2#2]
Happy New Year!

Subject says it all: do you plan to port this to gnuradio 3.10?

Cheers,
kai

**Comment by keyboarderror** [comment]
Happy New Year as well! I'd second that question, or suggest maybe a collaboration to add the HL2's PA control (and possibly filters) to gr-hpsdr which does have a GNURadio 3.10 branch. 

Thanks,
Jayson

**Comment by daniestevez** [comment]
Happy New Year everyone.

Changes to this OOT are not foreseen from my side in the near future, since I don't have enough bandwidth for this. So I won't be porting this to 3.9/3.10 (the same port should probably work for both) soon unless I suddenly find an experiment that I want to run with my HL2 and GNU Radio (as now I'm only running GNU Radio 3.10 in my machines, this would push me to port it).

Porting the OOT to 3.10 should be simple enough, specially since the modifications can be taken from gr-hpsdr. If someone wants to do the port themselves, by all means go ahead.

Speaking of which, it might be a good idea to move over the extra features that gr-hermeslite2 has to gr-hpsdr and deprecate gr-hermeslite2, since gr-hspdr is being developed more actively. When I forked gr-hpsdr, I gave little though to the idea of contributing to that OOT instead of forking. I simply wanted to experiment quickly and easily by adding new features specific to the HL2. In hindsight, maybe forking was a mistake.

The changes I have introduced in gr-hermeslite2 were done in a non-compatible way, in the sense that I modified things as made sense for the HL2 but didn't take into account other HPSDRs. It was assumed that gr-hermeslite2 would only support the HL2. So, to move the extra features of gr-hermeslite2 over to gr-hpsdr, it would be necessary to rewrite some things to make the HL2-specific features optional. I don't think this is going to happen any time soon, but I'm open to the idea.

**Comment by daniestevez** [comment]
> unless I suddenly find an experiment that I want to run with my HL2 and GNU Radio

It turns out that I want to record [these 34 MHz propagation tests](https://ei7gl.blogspot.com/2023/01/ei9kp-to-carry-out-34-mhz-propagation.html), so I have just ported gr-hermeslite2 to GNU Radio 3.10. This is now available on the main branch.

So far it seems that the port works well for me, but more testing would be appreciated. Then we can close this issue.

**Comment by kgarrels** [comment]
:-) super, thanks.

I will try it soon.

73,
kai

**Comment by keyboarderror** [comment]
That's great, thanks. A quick test shows transmit seems to be working fine, but the receive portion of my flow graph isn't. No audio.
73,
Jayson

**Comment by daniestevez** [comment]
@keyboarderror what do you mean by "no audio"? The "Hermes Lite 2 NB" block produces IQ data. It doesn't produce any audio per se. Can you share the flowgraph you're using? Receive is working just fine for me. This is what I'm currently using for the 34MHz propagation experiments.

**Comment by keyboarderror** [comment]
OK, I take it back. With some probing there is clearly an output on receive at the correct sample rates. So it may be my flow graph needs adjusting with the other changes in GR10. I will keep testing.

Thanks again!

**Comment by keyboarderror** [comment]
Operation has been intermittent. For reference on my flow graph I have a CQUAM am stereo modulator that I added a receiver I hope to make stereo some day. It receives (mono) audio correctly in GR3.8 And it will transmit in GR10.

I think there is a DC spur in the received I/Q that is stopping AM demodulation. (this is why I said no audio) FM demodulation gets through fine if I substitute that block. I can see a little AM in a GUI sink on the output along with a huge DC spike in the middle of the signal. Trying another way with the "complex to mag" block with a textbook layout also shows a DC spike.

Also, in other flow graphs in this installation I can't seem to activate the transmitter even if I hard set TX PTT mode on. I made a simple test with null inputs and outputs that should at least trip the HL2's relays on TX but nothing happens.

In trying again in a copy of Ubuntu 22.04.1 running directly on the hardware I can't get anything to work at all. It detects the network interface when I run the graph but stalls after showing the local interface and IP address. It doesn't connect to the HL2. Are there any other dependencies I could be missing?

Sorry if the report seems a bit jumbled, I'm still testing to see what I can get to work where.
73,
Jayson

**Comment by daniestevez** [comment]
Your problems don't seem related to the port to GNU Radio 3.10. The seem to have more to do with your flowgraphs, or with the Hermes code (`HermesProxy.cc` and `metis.cc`), which hasn't changed.

I don't think you're missing any dependencies if the OOT module built correctly. It seems more likely that you have a network problem.

**Comment by keyboarderror** [comment]
The network hasn't changed and does all work fine in 3.8. My successful tests are running in a 22.04.1 VM on a 20.04 host with a bridged network interface. It's a package based installation.  The machine next to it can boot 22.04.1 natively but the same graphs won't work there at all (adjusted for the different network interface) I don't always get the same results for a given configuration. Sometimes there's a spur sometimes not. Once I got a audible AM signal with complex to mag but not again after restarting the graph. The lack of consistency is very frustrating. Just trying to minimise the variables. I'm inclined to believe there are other issues with GR10 or my installations that this has only made apparent. I appreciate your efforts. I think this has just unlocked another level of my puzzle.

**Comment by GW4ABP-P** [comment]
Daniel,

Thanks for updating to GR3.10. Conducted initial tests this evening on my Hermes Lite 2 with GR SSB back end. All working OK on a Raspberry Pi4 with Ubuntu 22.04LTS 64 bit. LNA gain works OK. Will conduct TX tests over the next few days and try a PC running Ubuntu 22.04LTS. Further reports to follow. Mike G4ABP

**Comment by GW4ABP-P** [comment]
I have now tested my Hermes Lite 2 with GR3.10 on a Ubuntu 22.04LTS PC. All worked OK on receive. I've yet to try TX on a Raspberry Pi4 or a PC. This will require some investigation of the Hermes Filter board hardware. I need to check that the transmitter will be connected to the load before trying transmit. Not sure what the filter board does if it's not receiving relay instructions over Ethernet. For Raspberry Pi4 users - I noticed that I and Q are swapped around on the Pi. Mike G4ABP

**Comment by keyboarderror** [comment]
With a bit of time to troubleshoot I've got my AM receiver working. There seems to be an intermittent problem with the AGC block in my installation. Sometimes it fails to initialize and doesn't pass signal. Restarting GR10 seems to help. Bypassing it things work consistently. So, I just need to figure out why. Not an issue for here though. Thanks much.
73, AA7NM

**Comment by GW4ABP-P** [comment]
Message for Keyboarderror AA7NM.

My test show that there are serious faults in the GNU AGC functions. I don't know what they were designed for, but they are not suitable for use with analogue modes like SSB. The lack of documentation does not help. The time constants are a bit of a mystery. I found the same as yourself. Sometimes I get no audio, but restarting fixes it. There are well known performance criteria for Radio AGC systems, but GNU Radio AGC is not compliant. Note that if you are designing an AM radio, the AGC needs to operate on the carrier level. Not the Audio level. So you would have to make an AM AGC system out of other GNU Radio components. 

This subject is out of scope for Daniels HL2 interface, but just thought I'd pass on my experiences.

73, Mike, G4ABP

**Comment by daniestevez** [comment]
Hi, since it seems that gr-hermeslite2 works correctly on GNU Radio 3.10, I'm going to close this issue. Feel free to continue the ongoing discussions in this issue or perhaps to move them to the [hermes-lite mailing list](https://groups.google.com/g/hermes-lite), where they could be of interest to a wider audience.
